# Generated by Django 5.2.1 on 2025-05-18 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_account_created_at_account_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='price',
        ),
        migrations.RemoveField(
            model_name='key',
            name='product',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'إيداع'), ('PURCHASE', 'شراء'), ('WITHDRAWAL', 'سحب')], max_length=15),
        ),
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_categories', to='mainapp.product')),
            ],
            options={
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.AddField(
            model_name='key',
            name='price_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='mainapp.pricecategory'),
        ),
    ]
